version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  groups:
    python_dependencies:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  groups:
    gh_actions_dependencies:
      patterns:
        - "*"
